service: sls-discord-send-message

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3

functions:
  index:
    handler: index.handler
    description: Send messages to Discord
    events:
      - http:
          path: /
          method: get
          cors: true
